[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "userbot"
version = "0.1.0"
description = "telegram userbot"
readme = "README.md"
requires-python = ">=3.8"
    "pydantic",
    "pydantic-settings",
    "telethon",
    "qrcode",
    "deep-translator"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "mypy"
]
